### ISSUE TITLE
java support on linux

### ISSUE THREAD

**Issue by SauravDas90** [pakhandi/Buggy---Linux#4]
Hi, 

Can you extend this plugin for Java on Linux, it will be helpful for many users.

**Comment by pakhandi-zz** [comment]
V.4.2 is in testing and support for JAVA is included in this version.

**Comment by SauravDas90** [comment]
please provide us the download link. Great job sir!

**Comment by pakhandi-zz** [comment]
@SauravDas90 You can download the [current repository](https://github.com/pakhandi/Buggy---Linux/archive/master.zip) and try it out but it's not completely tested yet. If you find any bug please let me know :) .

**Comment by SauravDas90** [comment]
Ok will download and check it out.
